name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *' # Codziennie o 00:00 UTC
  workflow_dispatch: # Możliwość ręcznego uruchomienia

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps chromium

      - name: List files before running script
        run: ls -la

      - name: Run script
        run: python KW.py  # Nazwa Twojego skryptu

      - name: List files after running script
        run: ls -la

      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          # Dodajemy tylko istniejące pliki
          for file in output.txt errors.log proxy_errors.log; do
            [ -f "$file" ] && git add "$file"
          done
          git commit -m "Update results from script run" || echo "Nothing to commit"
          git push || echo "Push failed, but continuing"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}